export class HttpError extends Error {constructor(status,message){super(message);this.status=status;}}
const str=(value,max,required=false)=>{if(typeof value!=='string')value='';value=value.trim();if((required&&!value)||value.length>max)throw new HttpError(400,'Перевірте довжину обов’язкових полів.');return value;};
const number=(value,min,max,optional=false)=>{if(optional&&(value===''||value==null))return null;const n=Number(value);if(!Number.isFinite(n)||!Number.isInteger(n)||n<min||n>max)throw new HttpError(400,'Числові поля мають недопустиме значення.');return n;};
export function safeImage(value){if(typeof value!=='string')return false;return /^\/media\/[a-f0-9-]{36}$/.test(value)||/^https:\/\/olegwest1112-web\.github\.io\/formula-auto-bot\/assets\/[\w.-]+\.(jpg|png|webp)$/.test(value);}
export function validateVehicle(data){
 if(!data||typeof data!=='object')throw new HttpError(400,'Некоректний автомобіль.');
 const status=data.status;if(!['stock','road','sold','draft'].includes(status))throw new HttpError(400,'Невідомий статус.');
 const published=data.published===true&&status!=='draft';
 const images=Array.isArray(data.images)?[...new Set(data.images)]:[];if(images.length>24||images.some(p=>!safeImage(p)))throw new HttpError(400,'До 24 фотографій JPG, PNG або WebP.');
 const source=str(data.source,500);if(source&&!/^https:\/\/t\.me\/formula_auto_nv\/\d+$/.test(source))throw new HttpError(400,'Джерело: посилання на оголошення Formula у Telegram.');
 const equipment=Array.isArray(data.equipment)?data.equipment.map(v=>str(v,140,true)):[];if(equipment.length>50)throw new HttpError(400,'Максимум 50 опцій.');
 const payload={name:str(data.name,90,true),brand:str(data.brand,40,true),trim:str(data.trim,100),year:number(data.year,1950,new Date().getUTCFullYear()+1),price:number(data.price,1,2000000),mileageValue:number(data.mileageValue,0,3000000),mileageUnit:data.mileageUnit==='mi'?'mi':'km',engine:str(data.engine,80,true),fuel:str(data.fuel,30,true),gear:str(data.gear,30,true),drive:str(data.drive,30),body:str(data.body,30),vin:str(data.vin,17),description:str(data.description,10000),priceNote:str(data.priceNote,160),source,images,equipment,status,published};
 if(payload.vin&&!/^[A-HJ-NPR-Z0-9]{17}$/i.test(payload.vin))throw new HttpError(400,'VIN має містити 17 латинських літер та цифр без I, O, Q.');
 if(published&&!images.length)throw new HttpError(400,'Перед публікацією додайте хоча б одне фото.');
 return {...payload,internalNote:str(data.internalNote,2000),version:data.version};
}
export function publicVehicle(row){const car=JSON.parse(row.payload);return {...car,published:!!row.published,id:row.id,version:row.version,status:row.status,updatedAt:row.updated_at,mileage:`${new Intl.NumberFormat('uk-UA').format(car.mileageValue)} ${car.mileageUnit==='mi'?'миль':'км'}`};}
export function validateLead(data){const phone=str(data.phone,30,true);const digits=phone.replace(/[()\s-]/g,'');if(!/^\+?\d{9,15}$/.test(digits)||!/^\+?[\d()\s-]+$/.test(phone))throw new HttpError(400,'Вкажіть правильний номер телефону.');if(data.consent!==true)throw new HttpError(400,'Потрібна згода на обробку заявки.');if(!['consultation','viewing','tradein','import','finance'].includes(data.intent))throw new HttpError(400,'Оберіть тип звернення.');return {name:str(data.name,70,true),phone,intent:data.intent,carId:data.carId==null?null:number(data.carId,0,2147483647),comment:str(data.comment,700),ownCar:str(data.ownCar,150),budget:number(data.budget,0,2000000,true),consent:true,policyVersion:'2026-09-11'};}
export function validateSettings(data){if(!/^[a-zA-Z0-9_]{5,32}$/.test(String(data.managerUsername).replace(/^@/,''))||!/^[a-zA-Z0-9_]{5,32}$/.test(String(data.channelUsername).replace(/^@/,'')))throw new HttpError(400,'Перевірте Telegram username.');return {name:'Formula',phone:str(data.phone,30,true),address:str(data.address,200,true),hours:str(data.hours,160),managerUsername:str(data.managerUsername,32,true).replace(/^@/,''),channelUsername:str(data.channelUsername,32,true).replace(/^@/,''),instagram:'https://www.instagram.com/formula_avto_',testMode:data.testMode===true};}
export const defaultSettings={name:'Formula',phone:'+380778883344',address:'м. Нововолинськ, вул. Шахтарська, 27в',hours:'Час візиту узгодьте з менеджером',managerUsername:'beloeeet3535',channelUsername:'formulatestttt',instagram:'https://www.instagram.com/formula_avto_',testMode:true};
