import {HttpError,validateVehicle,publicVehicle,validateLead,validateSettings,defaultSettings} from './validation.js';
const json=(data,status=200)=>new Response(JSON.stringify(data),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const now=()=>new Date().toISOString();
const q=(env,sql,...args)=>env.DB.prepare(sql).bind(...args);
async function body(req){if(Number(req.headers.get('content-length'))>40000)throw new HttpError(413,'Забагато даних.');const text=await req.text();if(text.length>40000)throw new HttpError(413,'Забагато даних.');try{return JSON.parse(text);}catch{throw new HttpError(400,'Некоректні дані.');}}
async function settings(env){const row=await q(env,'SELECT * FROM settings WHERE id=1').first();return row?{...JSON.parse(row.payload),version:row.version}:{...defaultSettings,version:0};}
function owner(req,env){const email=req.headers.get('oai-authenticated-user-email')?.toLowerCase();return email&&(env.ADMIN_EMAILS||'').toLowerCase().split(',').map(s=>s.trim()).includes(email)?email:null;}
async function audit(env,actor,action,entity){await q(env,'INSERT INTO audit(actor,action,entity,created_at) VALUES(?,?,?,?)',actor,action,String(entity),now()).run();}
async function notify(env,id,payload){if(!env.MANAGER_CHAT_ID||!env.TELEGRAM_BOT_TOKEN)return false;try{const r=await fetch(`https://api.telegram.org/bot${env.TELEGRAM_BOT_TOKEN}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:env.MANAGER_CHAT_ID,text:`FORMULA • ${payload.testMode?'Тестова заявка':'Нова заявка'}\n№ ${id}\n${payload.name}\n${payload.phone}\nТип: ${payload.intent}\nАвто: ${payload.carName||'Підбір'}\n${payload.comment||''}\n${payload.ownCar||''}`})});const result=await r.json();if(!result.ok)return false;await q(env,'UPDATE leads SET notified=1 WHERE id=?',id).run();return true;}catch{return false;}}
async function route(req,env){
 const url=new URL(req.url),path=url.pathname.replace(/\/$/,'')||'/',method=req.method,actor=owner(req,env);
 if(path.startsWith('/admin')||path.startsWith('/api/admin')){
  if(!actor){if(path==='/admin'&&!req.headers.get('oai-authenticated-user-email'))return Response.redirect(url.origin+'/signin-with-chatgpt?return_to=%2Fadmin',302);throw new HttpError(403,'Доступ дозволено лише власнику Formula.');}
  if(!['GET','HEAD'].includes(method)&&req.headers.get('origin')!==url.origin)throw new HttpError(403,'Оновіть сторінку та повторіть дію.');
  if(path.startsWith('/admin')){const asset=typeof ADMIN_ASSETS!=='undefined'&&ADMIN_ASSETS[path];if(!asset)throw new HttpError(404,'Не знайдено.');return new Response(asset.body,{headers:{'Content-Type':asset.mime,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'self'; img-src 'self' https://olegwest1112-web.github.io blob:; style-src 'self'; script-src 'self'; connect-src 'self'; frame-ancestors 'none'; base-uri 'none'"}});}
 }
 if(path==='/'&&method==='GET')return Response.redirect('https://olegwest1112-web.github.io/formula-auto-bot/',302);
 if(path==='/api/catalog'&&method==='GET'){const rows=await q(env,'SELECT * FROM vehicles WHERE published=1 AND archived=0 ORDER BY id DESC').all();return json({cars:rows.results.map(publicVehicle),settings:await settings(env)});}
 if(path.startsWith('/media/')&&method==='GET'){const id=path.slice(7);if(!/^[a-f0-9-]{36}$/.test(id))throw new HttpError(404,'Фото не знайдено.');if(!actor){const used=await q(env,"SELECT vehicles.id FROM vehicles,json_each(vehicles.payload,'$.images') AS image WHERE published=1 AND archived=0 AND image.value=? LIMIT 1",path).first();if(!used)throw new HttpError(404,'Фото не знайдено.');}const object=await env.BUCKET.get(id);if(!object)throw new HttpError(404,'Фото не знайдено.');return new Response(object.body,{headers:{'Content-Type':object.httpMetadata?.contentType||'image/jpeg','Cache-Control':'private, max-age=60','X-Content-Type-Options':'nosniff'}});}
 if(path==='/api/leads'&&method==='POST'){
  const data=await body(req);if(data.website)throw new HttpError(400,'Не вдалося прийняти заявку.');const payload=validateLead(data),id=req.headers.get('Idempotency-Key');if(!/^[a-f0-9-]{36}$/.test(id||''))throw new HttpError(400,'Оновіть форму.');
  if(await q(env,'SELECT id FROM leads WHERE id=?',id).first())return json({id,stored:true});
  const ip=req.headers.get('cf-connecting-ip')||'unknown';const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode((env.RATE_LIMIT_SALT||'formula')+ip));const bucket=Math.floor(Date.now()/900000),key=Array.from(new Uint8Array(bytes),v=>v.toString(16).padStart(2,'0')).join('')+bucket;
  const limit=await q(env,'INSERT INTO rate_limits(id,count,expires) VALUES(?,1,?) ON CONFLICT(id) DO UPDATE SET count=count+1 RETURNING count',key,(bucket+1)*900000).first();if(limit.count>5)throw new HttpError(429,'Забагато спроб. Повторіть через 15 хвилин або напишіть менеджеру.');
  if(payload.carId!==null){const car=await q(env,"SELECT * FROM vehicles WHERE id=? AND published=1 AND archived=0 AND status IN ('stock','road')",payload.carId).first();if(!car)throw new HttpError(409,'Авто більше недоступне. Оновіть каталог.');payload.carName=JSON.parse(car.payload).name;}
  payload.testMode=(await settings(env)).testMode;const inserted=await q(env,'INSERT INTO leads(id,payload,created_at,updated_at) VALUES(?,?,?,?) ON CONFLICT(id) DO NOTHING RETURNING id',id,JSON.stringify(payload),now(),now()).first();if(!inserted)return json({id,stored:true});
  const notified=await notify(env,id,payload);await q(env,'DELETE FROM rate_limits WHERE expires<?',Date.now()).run();return json({id,stored:true,notified},201);
 }
 if(path==='/api/admin/me')return json({email:actor,notificationsConfigured:!!(env.MANAGER_CHAT_ID&&env.TELEGRAM_BOT_TOKEN)});
 if(path==='/api/admin/seed'&&method==='POST'){if(await q(env,'SELECT id FROM vehicles LIMIT 1').first())throw new HttpError(409,'Каталог уже заповнений. Імпорт доступний лише для порожньої бази.');const seed=typeof SEED!=='undefined'?SEED:[];await env.DB.batch(seed.map(data=>{const {internalNote,version,...car}=validateVehicle(data);return q(env,'INSERT INTO vehicles(id,payload,status,published,internal_note,created_at,updated_at) VALUES(?,?,?,?,?,?,?)',data.id,JSON.stringify(car),car.status,+car.published,internalNote,now(),now());}));await audit(env,actor,'catalog.initialize',seed.length);return json({imported:seed.length});}
 if(path==='/api/admin/vehicles'&&method==='GET'){const rows=await q(env,'SELECT * FROM vehicles ORDER BY id DESC').all();return json(rows.results.map(r=>({...publicVehicle(r),published:!!r.published,archived:!!r.archived,internalNote:r.internal_note})));}
 if(path==='/api/admin/vehicles'&&method==='POST'){const {internalNote,version,...car}=validateVehicle(await body(req));const row=await q(env,'INSERT INTO vehicles(payload,status,published,internal_note,created_at,updated_at) VALUES(?,?,?,?,?,?) RETURNING id',JSON.stringify(car),car.status,+car.published,internalNote,now(),now()).first();await audit(env,actor,'vehicle.create',row.id);return json({id:row.id},201);}
 const vehicle=path.match(/^\/api\/admin\/vehicles\/(\d+)(?:\/(archive|restore))?$/);
 if(vehicle&&method==='PUT'){
  const id=Number(vehicle[1]),data=await body(req);let changed;
  if(vehicle[2])changed=await q(env,'UPDATE vehicles SET archived=?,published=0,status=?,version=version+1,updated_at=? WHERE id=? AND version=? RETURNING id',vehicle[2]==='archive'?1:0,'draft',now(),id,Number(data.version)).first();
  else{const {internalNote,version,...car}=validateVehicle(data);changed=await q(env,'UPDATE vehicles SET payload=?,status=?,published=?,internal_note=?,version=version+1,updated_at=? WHERE id=? AND version=? AND archived=0 RETURNING id',JSON.stringify(car),car.status,+car.published,internalNote,now(),id,Number(version)).first();}
  if(!changed)throw new HttpError(409,'Запис змінився в іншій вкладці. Збережіть ваш текст і оновіть список.');await audit(env,actor,'vehicle.'+(vehicle[2]||'update'),id);return json({id});
 }
 if(path==='/api/admin/media'&&method==='POST'){
  if(Number(req.headers.get('content-length'))>8388608)throw new HttpError(413,'Фото має бути до 8 МБ.');const bytes=new Uint8Array(await req.arrayBuffer());if(bytes.length>8388608)throw new HttpError(413,'Фото має бути до 8 МБ.');let mime='';if(bytes[0]===255&&bytes[1]===216&&bytes[2]===255)mime='image/jpeg';else if(bytes.slice(0,8).join(',')==='137,80,78,71,13,10,26,10')mime='image/png';else if(new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP')mime='image/webp';if(!mime)throw new HttpError(400,'Оберіть JPG, PNG або WebP.');const id=crypto.randomUUID();await env.BUCKET.put(id,bytes,{httpMetadata:{contentType:mime}});try{await q(env,'INSERT INTO media(id,mime,size,created_at) VALUES(?,?,?,?)',id,mime,bytes.length,now()).run();}catch(e){await env.BUCKET.delete(id);throw e;}return json({url:'/media/'+id},201);
 }
 if(path==='/api/admin/settings'&&method==='GET')return json(await settings(env));
 if(path==='/api/admin/settings'&&method==='PUT'){const data=await body(req),payload=validateSettings(data);const row=Number(data.version)===0?await q(env,'INSERT INTO settings(id,payload,version) VALUES(1,?,1) ON CONFLICT(id) DO NOTHING RETURNING version',JSON.stringify(payload)).first():await q(env,'UPDATE settings SET payload=?,version=version+1 WHERE id=1 AND version=? RETURNING version',JSON.stringify(payload),Number(data.version)).first();if(!row)throw new HttpError(409,'Налаштування вже змінилися. Оновіть сторінку.');await audit(env,actor,'settings.update',1);return json({version:row.version});}
 if(path==='/api/admin/leads'&&method==='GET'){const rows=await q(env,'SELECT * FROM leads ORDER BY created_at DESC LIMIT 500').all();return json(rows.results.map(r=>({...JSON.parse(r.payload),id:r.id,status:r.status,notified:!!r.notified,version:r.version,createdAt:r.created_at})));}
 const lead=path.match(/^\/api\/admin\/leads\/([a-f0-9-]{36})(?:\/(retry))?$/);
 if(lead&&method==='PUT'){const row=await q(env,'SELECT * FROM leads WHERE id=?',lead[1]).first();if(!row)throw new HttpError(404,'Заявку не знайдено.');if(lead[2]){if(row.notified)return json({notified:true});return json({notified:await notify(env,row.id,JSON.parse(row.payload))});}const data=await body(req);if(!['new','contacted','closed'].includes(data.status))throw new HttpError(400,'Невідомий статус.');const changed=await q(env,'UPDATE leads SET status=?,version=version+1,updated_at=? WHERE id=? AND version=? RETURNING id',data.status,now(),row.id,Number(data.version)).first();if(!changed)throw new HttpError(409,'Заявка вже змінилася. Оновіть список.');await audit(env,actor,'lead.'+data.status,row.id);return json({id:row.id});}
 if(path==='/api/admin/audit'&&method==='GET')return json((await q(env,'SELECT * FROM audit ORDER BY id DESC LIMIT 100').all()).results);
 throw new HttpError(404,'Сторінку не знайдено.');
}
export default {async fetch(req,env){const origin=req.headers.get('origin'),allowed=origin==='https://olegwest1112-web.github.io'||origin===new URL(req.url).origin;let response;if(req.method==='OPTIONS')response=new Response(null,{status:204});else try{response=await route(req,env);}catch(e){response=json({error:e instanceof HttpError?e.message:'Тимчасова помилка сервера. Повторіть спробу.'},e instanceof HttpError?e.status:500);}const headers=new Headers(response.headers);if(allowed){headers.set('Access-Control-Allow-Origin',origin);headers.set('Vary','Origin');headers.set('Access-Control-Allow-Methods','GET,POST,PUT,OPTIONS');headers.set('Access-Control-Allow-Headers','Content-Type,Idempotency-Key');}return new Response(response.body,{status:response.status,headers});}};
