import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import fs from 'node:fs';
import worker from '../backend/worker.js';
import {validateVehicle} from '../backend/validation.js';
function database(){const db=new DatabaseSync(':memory:');for(const file of fs.readdirSync('drizzle').filter(f=>f.endsWith('.sql')))db.exec(fs.readFileSync('drizzle/'+file,'utf8'));const prepare=sql=>({bind(...args){return {async first(){return db.prepare(sql).get(...args)||null;},async all(){return {results:db.prepare(sql).all(...args)};},async run(){return db.prepare(sql).run(...args);}};}});return {prepare,async batch(statements){db.exec('BEGIN');try{const out=[];for(const s of statements)out.push(await s.run());db.exec('COMMIT');return out;}catch(e){db.exec('ROLLBACK');throw e;}}};}
function setup(){const env={DB:database(),ADMIN_EMAILS:'owner@example.com',BUCKET:{},RATE_LIMIT_SALT:'test'};const call=async(path,method='GET',data,auth=true,extra={})=>{const headers={'Content-Type':'application/json',origin:'https://formula.test',...(auth?{'oai-authenticated-user-email':'owner@example.com'}:{}),...extra};return worker.fetch(new Request('https://formula.test'+path,{method,headers,body:data===undefined?undefined:JSON.stringify(data)}),env);};return {env,call};}
const car={name:'Audi Q5',brand:'Audi',year:2016,price:13990,mileageValue:191000,mileageUnit:'km',engine:'2.0',fuel:'Бензин',gear:'Автомат',status:'draft',published:false,images:[],internalNote:'PRIVATE'};
test('admin requires owner identity and same-origin mutations',async()=>{const {call}=setup();assert.equal((await call('/api/admin/vehicles','GET',undefined,false)).status,403);assert.equal((await call('/api/admin/vehicles','GET',undefined,true,{'oai-authenticated-user-email':'wrong@example.com'})).status,403);assert.equal((await call('/api/admin/vehicles','POST',car,true,{origin:'https://attacker.test'})).status,403);assert.equal((await call('/admin','GET',undefined,false)).status,302);});
test('drafts, publication, optimistic lock and archive restore',async()=>{const {call}=setup();const created=await call('/api/admin/vehicles','POST',car);assert.equal(created.status,201);const {id}=await created.json();assert.equal((await (await call('/api/catalog')).json()).cars.length,0);const published={...car,status:'stock',published:true,images:['https://olegwest1112-web.github.io/formula-auto-bot/assets/car-0-0.jpg'],version:1};assert.equal((await call('/api/admin/vehicles/'+id,'PUT',published)).status,200);let catalog=await (await call('/api/catalog')).json();assert.equal(catalog.cars.length,1);assert.equal(catalog.cars[0].internalNote,undefined);assert.equal(JSON.stringify(catalog).includes('PRIVATE'),false);assert.equal((await call('/api/admin/vehicles/'+id,'PUT',published)).status,409);assert.equal((await call('/api/admin/vehicles/'+id+'/archive','PUT',{version:2})).status,200);assert.equal((await (await call('/api/catalog')).json()).cars.length,0);assert.equal((await call('/api/admin/vehicles/'+id+'/restore','PUT',{version:3})).status,200);const rows=await (await call('/api/admin/vehicles')).json();assert.equal(rows[0].published,false);assert.equal(rows[0].status,'draft');});
test('settings create and subsequent update preserve optimistic locking',async()=>{const {call}=setup();const s=await (await call('/api/admin/settings')).json();assert.equal((await call('/api/admin/settings','PUT',s)).status,200);assert.equal((await call('/api/admin/settings','PUT',{...s,version:1,hours:'За записом'})).status,200);assert.equal((await call('/api/admin/settings','PUT',{...s,version:1})).status,409);assert.equal((await (await call('/api/catalog')).json()).settings.hours,'За записом');});
test('lead stores once, validates consent, hides private records and handles notification unavailable',async()=>{const {call}=setup();const id=crypto.randomUUID(),data={name:'Тест',phone:'+380991234567',intent:'consultation',consent:true};let r=await call('/api/leads','POST',data,false,{'Idempotency-Key':id});assert.equal(r.status,201);assert.equal((await r.json()).notified,false);r=await call('/api/leads','POST',data,false,{'Idempotency-Key':id});assert.equal(r.status,200);assert.equal((await (await call('/api/admin/leads')).json()).length,1);assert.equal((await call('/api/admin/leads','GET',undefined,false)).status,403);assert.equal((await call('/api/leads','POST',{...data,consent:false},false,{'Idempotency-Key':crypto.randomUUID()})).status,400);assert.equal((await call('/api/leads','POST',{...data,carId:999},false,{'Idempotency-Key':crypto.randomUUID()})).status,409);});
test('rate limit and public CORS',async()=>{const {call}=setup();for(let i=0;i<5;i++)assert.equal((await call('/api/leads','POST',{name:'Test',phone:'+380991234567',intent:'import',consent:true},false,{'Idempotency-Key':crypto.randomUUID()})).status,201);assert.equal((await call('/api/leads','POST',{name:'Test',phone:'+380991234567',intent:'import',consent:true},false,{'Idempotency-Key':crypto.randomUUID()})).status,429);const r=await call('/api/catalog','GET',undefined,false,{origin:'https://olegwest1112-web.github.io'});assert.equal(r.headers.get('Access-Control-Allow-Origin'),'https://olegwest1112-web.github.io');});
test('photo and published vehicle validation reject active content and missing cover',()=>{assert.throws(()=>validateVehicle({...car,status:'stock',published:true}));assert.throws(()=>validateVehicle({...car,images:['javascript:alert(1)']}));assert.throws(()=>validateVehicle({...car,vin:'INVALID'}));});
