const $=s=>document.querySelector(s),escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={stock:'У наявності',road:'У дорозі',sold:'Продано',draft:'Чернетка',new:'Нова',contacted:'У роботі',closed:'Закрита'};
let page='vehicles',cars=[],leads=[],editing=null,photos=[],dirty=false,busy=false;
async function api(path,method='GET',data){const response=await fetch('/api/admin/'+path,{method,headers:data instanceof File?{'Content-Type':data.type}:{'Content-Type':'application/json'},body:data===undefined?undefined:data instanceof File?data:JSON.stringify(data)});const result=await response.json();if(!response.ok)throw new Error(result.error||'Помилка сервера');return result;}
const notice=text=>$('#notice').textContent=text;
const fields=[['name','Назва автомобіля','text',true],['brand','Марка','text',true],['trim','Версія / комплектація'],['year','Рік','number',true],['price','Ціна, $','number',true],['priceNote','Уточнення до ціни'],['mileageValue','Пробіг','number',true],['mileageUnit','Одиниця пробігу',['km','mi']],['engine','Двигун','text',true],['fuel','Пальне',['Бензин','Дизель','Гібрид','Електро','Газ / бензин']],['gear','Коробка',['Автомат','Механіка','Робот','Варіатор']],['drive','Привід'],['body','Кузов'],['vin','VIN'],['status','Статус',['draft','stock','road','sold']],['source','Посилання на оголошення']];
$('#vehicle-fields').innerHTML=fields.map(([name,label,type='text',required])=>`<label>${label}${Array.isArray(type)?`<select name="${name}">${type.map(v=>`<option value="${v}">${labels[v]||({km:'Кілометри',mi:'Милі'}[v])||v}</option>`).join('')}</select>`:`<input name="${name}" type="${type}" ${required?'required':''} ${type==='number'?'min="0" step="1"':''} maxlength="${name==='vin'?17:500}">`}</label>`).join('');
function close(){if(busy)return;if(dirty&&!confirm('Закрити без збереження змін?'))return;$('#editor').close();dirty=false;}
$('#close').onclick=close;$('#editor').addEventListener('cancel',e=>{e.preventDefault();close();});window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});$('#vehicle-form').addEventListener('input',()=>dirty=true);
function renderPhotos(){$('#photo-count').textContent=`${photos.length}/24`;$('#photos').innerHTML=photos.map((src,i)=>`<figure><img src="${escape(src)}" alt="Фото ${i+1}"><div class="actions"><button type="button" data-photo="up" data-index="${i}" ${i===0?'disabled':''}>←</button><button type="button" data-photo="down" data-index="${i}" ${i===photos.length-1?'disabled':''}>→</button><button type="button" data-photo="remove" data-index="${i}">Видалити</button></div><small>${i===0?'Обкладинка':i+1}</small></figure>`).join('');}
$('#photos').onclick=e=>{const b=e.target.closest('[data-photo]');if(!b)return;const i=+b.dataset.index,j=b.dataset.photo==='up'?i-1:i+1;if(b.dataset.photo==='remove')photos.splice(i,1);else [photos[i],photos[j]]=[photos[j],photos[i]];dirty=true;renderPhotos();};
function edit(car){editing=car||null;const f=$('#vehicle-form');f.reset();$('#form-error').textContent='';$('#editor-title').textContent=car?'Редагувати автомобіль':'Додати автомобіль';for(const [name] of fields)if(car&&car[name]!=null){if(f.elements[name].tagName==='SELECT'&&![...f.elements[name].options].some(o=>o.value===String(car[name])))f.elements[name].add(new Option(car[name],car[name]));f.elements[name].value=car[name];}for(const name of ['description','internalNote'])f.elements[name].value=car?.[name]||'';f.elements.equipment.value=(car?.equipment||[]).join('\n');f.elements.published.checked=car?.published||false;photos=[...(car?.images||[])];renderPhotos();dirty=false;$('#editor').showModal();}
$('#upload').onchange=async e=>{const files=[...e.target.files];if(photos.length+files.length>24){$('#form-error').textContent='Максимум 24 фотографії.';return;}busy=true;$('#save').disabled=true;$('#upload').disabled=true;try{for(const file of files){if(file.size>8388608)throw new Error(`${file.name}: фото має бути до 8 МБ.`);const result=await api('media','POST',file);photos.push(result.url);dirty=true;renderPhotos();}$('#form-error').textContent='';}catch(error){$('#form-error').textContent=error.message;}finally{busy=false;$('#save').disabled=false;$('#upload').disabled=false;e.target.value='';}};
$('#vehicle-form').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;$('#save').disabled=true;try{const data=Object.fromEntries(new FormData(e.target));data.images=photos;data.equipment=data.equipment.split('\n').map(s=>s.trim()).filter(Boolean);data.published=e.target.elements.published.checked;data.version=editing?.version;await api('vehicles'+(editing?'/'+editing.id:''),editing?'PUT':'POST',data);dirty=false;$('#editor').close();await load();notice('Автомобіль збережено. Каталог відображає опубліковані картки.');}catch(error){$('#form-error').textContent=error.message;}finally{busy=false;$('#save').disabled=false;}};
function inventory(){const query=($('#search')?.value||'').toLowerCase(),status=$('#filter')?.value||'all';const filtered=cars.filter(c=>(c.name+' '+c.vin).toLowerCase().includes(query)&&(status==='all'?!c.archived:status==='archive'?c.archived:!c.archived&&c.status===status));$('#list').innerHTML=filtered.length?filtered.map(c=>`<article class="card">${c.images[0]?`<img src="${escape(c.images[0])}" alt="">`:''}<div class="info"><h3>${escape(c.name)}</h3><p>${c.year} · $${Number(c.price).toLocaleString('uk-UA')} · ${escape(c.mileage)}</p><span class="tag">${c.archived?'Архів':labels[c.status]}</span> <span class="tag">${c.published&&!c.archived?'Опубліковано':'Приховано'}</span></div><div class="actions">${!c.archived?`<button data-edit="${c.id}">Редагувати</button><button data-archive="${c.id}">До архіву</button>`:`<button data-restore="${c.id}">Відновити як чернетку</button>`}</div></article>`).join(''):'<div class="empty">Автомобілів поки немає. Додайте першу картку або змініть фільтри.</div>';}
async function load(){notice('');$('#content').setAttribute('aria-busy','true');try{if(page==='vehicles'){cars=await api('vehicles');$('#content').innerHTML=`<div class="stats"><div><b>${cars.filter(c=>!c.archived&&c.published).length}</b>У каталозі</div><div><b>${cars.filter(c=>!c.archived&&!c.published).length}</b>Чернетки / приховані</div><div><b>${cars.filter(c=>c.archived).length}</b>В архіві</div></div><div class="toolbar"><input id="search" placeholder="Пошук за назвою або VIN" aria-label="Пошук"><select id="filter"><option value="all">Усі активні</option>${Object.entries(labels).slice(0,4).map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}<option value="archive">Архів</option></select><button class="primary" id="add">+ Додати авто</button><button id="export">Експорт JSON</button></div><div id="list"></div>`;$('#search').oninput=inventory;$('#filter').onchange=inventory;$('#add').onclick=()=>edit();$('#export').onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(cars,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='formula-inventory.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};inventory();if(!cars.length){const b=document.createElement('button');b.className='primary';b.textContent='Завантажити початкові 4 авто з каналу';b.onclick=async()=>{b.disabled=true;try{await api('seed','POST',{});await load();}catch(e){notice(e.message);b.disabled=false;}};$('#list').append(b);}}
 else if(page==='leads'){leads=await api('leads');$('#content').innerHTML=`<p class="hint">Заявки доступні лише власнику. Максимум 500 останніх. Нова: очікує контакту; у роботі: менеджер зв’язався; закрита: звернення завершене.</p>${leads.length?leads.map(l=>`<article class="card lead"><div class="info"><h3>${escape(l.name)} ${l.testMode?'<span class="tag">Тестова</span>':''}</h3><a href="tel:${escape(l.phone.replace(/[^+\d]/g,''))}">${escape(l.phone)}</a><p>${escape(l.carName||'Підбір авто')} · ${escape(l.intent)}</p><p>${escape(l.comment)} ${escape(l.ownCar)}</p><small>${new Date(l.createdAt).toLocaleString('uk-UA')} · № ${l.id.slice(0,8)}</small><p>${l.notified?'✓ Повідомлення доставлено в Telegram':'Повідомлення не доставлено — заявка збережена'}</p></div><div class="actions"><select data-lead="${l.id}" aria-label="Статус заявки">${['new','contacted','closed'].map(s=>`<option value="${s}" ${l.status===s?'selected':''}>${labels[s]}</option>`).join('')}</select>${!l.notified?`<button data-retry="${l.id}">Повторити сповіщення</button>`:''}</div></article>`).join(''):'<div class="empty">Нові заявки з каталогу з’являться тут.</div>'}`;}
 else if(page==='settings'){const s=await api('settings');$('#content').innerHTML=`<form id="settings" class="settings"><h2>Контакти компанії</h2>${[['phone','Телефон'],['address','Адреса'],['hours','Графік / умови візиту'],['managerUsername','Telegram менеджера'],['channelUsername','Telegram каналу']].map(([n,l])=>`<label>${l}<input name="${n}" value="${escape(s[n])}" required maxlength="200"></label>`).join('')}<label class="check"><input type="checkbox" name="testMode" ${s.testMode?'checked':''}>Тестовий режим: позначати заявки як тестові</label><p class="hint">Особисті сповіщення підключені до @beloeeet3535. Зміна посилання вище не змінює захищеного отримувача бота.</p><button class="primary">Зберегти налаштування</button></form>`;$('#settings').onsubmit=async e=>{e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{await api('settings','PUT',{...Object.fromEntries(new FormData(e.target)),testMode:e.target.elements.testMode.checked,version:s.version});await load();notice('Налаштування збережено.');}catch(error){notice(error.message);button.disabled=false;}};}
 else{const rows=await api('audit');$('#content').innerHTML='<p class="hint">Останні 100 змін. Персональні дані заявок не записуються в цей журнал.</p>'+rows.map(r=>`<div class="audit">${escape(r.action)} · ${escape(r.entity)}<small>${escape(r.actor)} · ${new Date(r.created_at).toLocaleString('uk-UA')}</small></div>`).join('');}
 }catch(error){notice(error.message);}finally{$('#content').removeAttribute('aria-busy');}}
document.querySelector('nav').onclick=e=>{const b=e.target.closest('[data-page]');if(!b)return;page=b.dataset.page;document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x===b));$('#title').textContent=b.textContent;load();};$('#refresh').onclick=load;
$('#content').onclick=async e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.edit){edit(cars.find(c=>c.id===+b.dataset.edit));return;}const action=b.dataset.archive?'archive':b.dataset.restore?'restore':b.dataset.retry?'retry':null;if(!action)return;const id=b.dataset[action];if(action==='archive'&&!confirm('Приховати автомобіль і перемістити до архіву? Його можна буде відновити.'))return;b.disabled=true;try{if(action==='retry'){const result=await api('leads/'+id+'/retry','PUT',{});await load();if(!result.notified)notice('Telegram поки не прийняв повідомлення. Заявка залишається збереженою.');}else{await api('vehicles/'+id+'/'+action,'PUT',{version:cars.find(c=>c.id===+id).version});await load();}}catch(error){notice(error.message);b.disabled=false;}};
$('#content').onchange=async e=>{if(!e.target.dataset.lead)return;const id=e.target.dataset.lead;e.target.disabled=true;try{await api('leads/'+id,'PUT',{status:e.target.value,version:leads.find(l=>l.id===id).version});await load();}catch(error){notice(error.message);e.target.disabled=false;}};
api('me').then(user=>{$('#account').textContent=user.email;if(!user.notificationsConfigured)notice('Сповіщення ще не підключені.');}).catch(e=>notice(e.message));load();
