import fs from 'node:fs';
fs.mkdirSync('build/server',{recursive:true});fs.mkdirSync('build/.openai',{recursive:true});
const files={'/admin':['admin/index.html','text/html; charset=utf-8'],'/admin/app.js':['admin/app.js','text/javascript; charset=utf-8'],'/admin/style.css':['admin/style.css','text/css; charset=utf-8']};
const assets=Object.fromEntries(Object.entries(files).map(([url,[path,mime]])=>[url,{body:fs.readFileSync(path,'utf8'),mime}]));
const modules=['validation','auth','company','bot','inventory'].map(name=>fs.readFileSync(`backend/${name}.js`,'utf8').replace(/^import .*;\r?\n/gm,'').replaceAll('export ',''));
const worker=fs.readFileSync('backend/worker.js','utf8').replace(/^import .*;\r?\n/gm,'');
const source=JSON.parse(fs.readFileSync('backend/source-catalog.json','utf8'));
fs.writeFileSync('build/server/index.js',`const ADMIN_ASSETS=${JSON.stringify(assets)};\nconst SOURCE_CATALOG=${JSON.stringify(source)};\n${modules.join('\n')}\n${worker}`);
fs.copyFileSync('.openai/hosting.json','build/.openai/hosting.json');fs.cpSync('drizzle','build/.openai/drizzle',{recursive:true});
console.log('Formula Worker built: company access, catalog, leads, photo storage');
